### ISSUE TITLE
Odd scaling behavior with low targetMessagesPerWorker

### ISSUE THREAD

**Issue by nvelaborja** [practo/k8s-worker-pod-autoscaler#32] opened 2019-09-11 18:32 UTC
Set the following options just to test the autoscaler 
`minReplicas: 1
  maxReplicas: 8
  targetMessagesPerWorker: 1
  --resync-period=1
  --wpa-threads=100
  --aws-region=us-west-2
  --sqs-short-poll-interval=1
  --sqs-long-poll-interval=1`

and noticed some strange behavior in scaling that I can't explain. With a no messages on the queue, one pod is spun up as expected. Then when I enqueued a second message, the autoscaler spun up max replicas (8), then terminated all but two, then slowly started spinning up new replicas one at a time back up to max replicas (8). 

I played around with the configuration, thread count, and poll times but still kept getting this result. Not sure if my understanding of "targetMessagesPerWorker" is off or if this is a bug, but thought I'd mention it.

**Comment by alok87** [comment] 2019-09-18 11:50
Let me check and get back. I'll try reproducing this.

**Comment by alok87** [comment] 2019-09-18 12:07
`--resync-period=1` is very low a value. You should use default or set it higher. This sets the kubernetes events sync to 1 second. https://godoc.org/k8s.io/client-go/informers#NewSharedInformerFactory Why do you need a 1 second sync?
`--sqs-short-poll-interval=1 ` Short poll interval is the interval at which AWS SQS is checked for queue length. With 1 second interval you may get rate limited if your queues are many by AWS. Again why do you really need it to be 1 second?
`--sqs-long-poll-interval=1` If you are using long polling you should make use of the maximum number of seconds you can long poll which is 20 seconds allowed by AWS.

So unless required we should be using the default values.

TargetMessagesPerWorker is the target metric which will scale your workers from min to max with every tick if the current value is above the target. (just like CPU target scaling happens)
Target messages per worker name is given because of the calculation used to determine the number https://github.com/practo/k8s-worker-pod-autoscaler/blob/master/pkg/controller/controller.go#L355-L397

The odd behaviour you see is because cooldown yet. And with every resync period tick the autoscaler scales if the actual queue length has not come down below target Queue length.

If you explain your use case, it would be better to suggest how to use WPA.

**Comment by alok87** [comment] 2019-10-21 13:32
Closing this as there is no odd scaling behaviour. Parameters for WPA needs to be configured properly or use defaults.
Please reopen this if you still have any concern.

**Closed by alok87** 2019-10-21 13:32 UTC
