### ISSUE TITLE
DesiredWorkers more than MaxWorkers

### ISSUE THREAD

**Issue by ishanjoshi02** [practo/k8s-worker-pod-autoscaler#70] opened 2020-05-18 14:05 UTC
![image](https://user-images.githubusercontent.com/14982214/82222260-aa282080-993e-11ea-8441-338cae9cef12.png)

**Comment by alok87** [comment] 2020-06-12 11:55
Closing this, not reproducible, looks like some UI issue there.

**Comment by alok87** [comment] 2020-07-07 13:47
desired=357 when max=10.

```
I0707 13:45:28.042337       1 controller.go:552] prod-phoenix-qikwell-maxwell-sync min=2, max=10, targetBacklog=2500
I0707 13:45:28.042366       1 controller.go:573] prod-phoenix-qikwell-maxwell-sync qMsgs=1, qMsgsPerMin=2136.6
I0707 13:45:28.042387       1 controller.go:575] prod-phoenix-qikwell-maxwell-sync secToProcessJob=10, maxDisruption=0xc00151eec0
I0707 13:45:28.042407       1 controller.go:577] prod-phoenix-qikwell-maxwell-sync current=10, idle=0
I0707 13:45:28.042417       1 controller.go:579] prod-phoenix-qikwell-maxwell-sync minComputed=357, maxDisruptable=0
I0707 13:45:28.042435       1 controller.go:581] prod-phoenix-qikwell-maxwell-sync usageRatio=0.0004
I0707 13:45:28.042455       1 controller.go:411] prod-phoenix-qikwell-maxwell-sync qMsgs: 1, desired: 357
I0707 13:45:32.412413       1 controller.go:552] prod-phoenix-qikwell-maxwell-sync min=2, max=10, targetBacklog=2500
I0707 13:45:32.412460       1 controller.go:573] prod-phoenix-qikwell-maxwell-sync qMsgs=1, qMsgsPerMin=2136.6
I0707 13:45:32.412488       1 controller.go:575] prod-phoenix-qikwell-maxwell-sync secToProcessJob=10, maxDisruption=0xc00186c010
I0707 13:45:32.412502       1 controller.go:577] prod-phoenix-qikwell-maxwell-sync current=10, idle=0
I0707 13:45:32.412512       1 controller.go:579] prod-phoenix-qikwell-maxwell-sync minComputed=357, maxDisruptable=0
I0707 13:45:32.412521       1 controller.go:581] prod-phoenix-qikwell-maxwell-sync usageRatio=0.0004
I0707 13:45:32.412532       1 controller.go:411] prod-phoenix-qikwell-maxwell-sync qMsgs: 1, desired: 357
```

**Closed** 2020-07-07 14:29 UTC
